### ISSUE TITLE
Mising CH340/usb-ttl support am32 direct connect support

### ISSUE THREAD

**Issue by ss8688** [stylesuxx/esc-configurator#432] opened 2023-12-01 01:32 UTC
I am using am32 on a Crawler. Don't have a controller. Hope you can support am32 direct connect

**Comment by stylesuxx** [comment] 2023-12-01 02:32
Closing this as it's a duplicate of #37.

I've been working on a 4 way interface implementation via Arduino, this would be more flexible. It's on the back-burner though, so don't expect it any time soon.

**Closed by stylesuxx** 2023-12-01 02:32 UTC
Labels: duplicate, feature request
